### ISSUE TITLE
Sites in servers are not using a paginator or custom limit

### ISSUE THREAD

**Issue by SebastiaanKloos** [ploi-deploy/ploi-raycast#1]
The result is limited to 15 items at the moment

**Comment by Cannonb4ll** [comment]
For now, paginating can be quite difficult unless your while'ing through all records. I could make a button "Load more" under the 15 limited results, but that would result in the search not working.

For now, I've just set the limit per_page to 50 in commit f659abbf222acd1b64e03f679347df01defe37a2, I personally consider 50 sites excessive for a single server and do not expect that the numbers would go any higher than that.

**Comment by SebastiaanKloos** [comment]
@Cannonb4ll 50 is indeed enough in most of the cases. Thanks 🙏
