### ISSUE TITLE
Open SSH session in other terminals like iTerm

### ISSUE THREAD

**Issue by SebastiaanKloos** [ploi-deploy/ploi-raycast#2]
Currently all sessions open in the default terminal application. As discussed earlier, it would be awesome to open them in iTerm.

**Comment by Cannonb4ll** [comment]
@SebastiaanKloos Would you be able to take a look at this?

**Comment by SebastiaanKloos** [comment]
For reference

https://ma.ttias.be/set-iterm2-default-ssh-handler-mac-osx/

**Comment by SebastiaanKloos** [comment]
@Cannonb4ll I think users should enable it on their mac instead of us creating a solution as it's a system wide setting.

See article above for some information about how to set it all up.

**Comment by Cannonb4ll** [comment]
Thanks!
